
#
# Super simple example of a Dockerfile
#

FROM nginx:latest
MAINTAINER Mystique "miztiik@github"

ADD index.html /usr/share/nginx/html/index.html
# COPY static-html-directory /usr/share/nginx/html

